import { UserDetails } from "src/services/interfaces";

  export const users: UserDetails[] = [
    {
      username: "kjimmison0",
      joined_at: "2023-01-15",
      bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      profile_image: "http://dummyimage.com/118x100.png/ff4444/ffffff",
      follows_user: true,
      user_id: "1",
      follows: true,
      followed: false,
      followers: 120,
      posts: 15,
      following: 85
    },
    {
      username: "ccrosgrove1",
      joined_at: "2022-12-05",
      bio: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      profile_image: "http://dummyimage.com/233x100.png/ff4444/ffffff",
      follows_user: false,
      user_id: "2",
      follows: false,
      followed: true,
      followers: 98,
      posts: 25,
      following: 60
    },
    {
      username: "zmcruvie3",
      joined_at: "2023-03-20",
      bio: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      profile_image: "http://dummyimage.com/139x100.png/5fa2dd/ffffff",
      follows_user: true,
      user_id: "3",
      follows: true,
      followed: true,
      followers: 150,
      posts: 30,
      following: 110
    },
    {
      username: "djozefowicz3",
      joined_at: "2023-02-10",
      bio: "Duis aute irure dolor in reprehererit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      profile_image: "http://dummyimage.com/149x100.png/cc0000/ffffff",
      follows_user: false,
      user_id: "4",
      follows: false,
      followed: false,
      followers: 75,
      posts: 10,
      following: 45
    },
    {
      username: "ksmiths4",
      joined_at: "2023-04-18",
      bio: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      profile_image: "http://dummyimage.com/191x100.png/cc0000/ffffff",
      follows_user: true,
      user_id: "5",
      follows: true,
      followed: true,
      followers: 200,
      posts: 40,
      following: 180
    },
    {
      username: "sgori5",
      joined_at: "2023-05-12",
      bio: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
      profile_image: "http://dummyimage.com/247x100.png/dddddd/000000",
      follows_user: false,
      user_id: "6",
      follows: false,
      followed: true,
      followers: 180,
      posts: 35,
      following: 95
    },
    {
      username: "gplewright6",
      joined_at: "2023-06-25",
      bio: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.",
      profile_image: "http://dummyimage.com/152x100.png/5fa2dd/ffffff",
      follows_user: true,
      user_id: "7",
      follows: true,
      followed: false,
      followers: 110,
      posts: 20,
      following: 75
    },
    {
      username: "fdanelet7",
      joined_at: "2023-07-10",
      bio: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
      profile_image: "http://dummyimage.com/159x100.png/dddddd/000000",
      follows_user: false,
      user_id: "8",
      follows: false,
      followed: true,
      followers: 95,
      posts: 28,
      following: 50
    },
    {
      username: "ehovey8",
      joined_at: "2023-08-05",
      bio: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.",
      profile_image: "http://dummyimage.com/217x100.png/cc0000/ffffff",
      follows_user: true,
      user_id: "9",
      follows: true,
      followed: true,
      followers: 250,
      posts: 50,
      following: 200
    },
    {
      username: "rsmiley9",
      joined_at: "2023-09-15",
      bio: "Et harum quidem rerum facilis est et expedita distinctio.",
      profile_image: "http://dummyimage.com/137x100.png/5fa2dd/ffffff",
      follows_user: false,
      user_id: "10",
      follows: false,
      followed: false,
      followers: 80,
      posts: 18,
      following: 60
    },
    {
      username: "jedlestona",
      joined_at: "2023-10-20",
      bio: "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.",
      profile_image: "http://dummyimage.com/249x100.png/ff4444/ffffff",
      follows_user: true,
      user_id: "11",
      follows: true,
      followed: false,
      followers: 300,
      posts: 60,
      following: 250
    },
    {
      username: "lcullb",
      joined_at: "2023-11-25",
      bio: "Omnis voluptas assumenda est, omnis dolor repellendus.",
      profile_image: "http://dummyimage.com/169x100.png/ff4444/ffffff",
      follows_user: false,
      user_id: "12",
      follows: false,
      followed: true,
      followers: 130,
      posts: 22,
      following: 90
    },
    {
      username: "dpratchettc",
      joined_at: "2024-01-05",
      bio: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
      profile_image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
      follows_user: true,
      user_id: "13",
      follows: true,
      followed: true,
      followers: 180,
      posts: 45,
      following: 120
    },
    {
      username: "dlillemand",
      joined_at: "2024-02-15",
      bio: "Itaque earum rerum hic tenetur a sapiente delectus.",
      profile_image: "http://dummyimage.com/241x100.png/5fa2dd/ffffff",
      follows_user: false,
      user_id: "14",
      follows: false,
      followed: false,
      followers: 90,
      posts: 30,
      following: 70
    },
    {
      username: "rtreacye",
      joined_at: "2024-03-25",
      bio: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      profile_image: "http://dummyimage.com/184x100.png/dddddd/000000",
      follows_user: true,
      user_id: "15",
      follows: true,
      followed: true,
      followers: 220,
      posts: 55,
      following: 180
    },
    {
        username: "mweld0",
        joined_at: "2024-01-05",
        bio: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
        profile_image: "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQ7xetZazndXzsY-Wos8xN576trcmTX8gHc3wunT8NOh6a03Svy2LrQhrMvV7NVzbEkyXliR9pSMbuwO_4",
        follows_user: true,
        user_id: "13",
        follows: true,
        followed: true,
        followers: 180,
        posts: 45,
        following: 120
    },
    {
        username: "mweld1",
        joined_at: "2024-01-05",
        bio: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
        profile_image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
        follows_user: true,
        user_id: "13",
        follows: true,
        followed: true,
        followers: 180,
        posts: 45,
        following: 120
    },
    {
        username: "tdannett1",
        joined_at: "2024-01-05",
        bio: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
        profile_image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
        follows_user: true,
        user_id: "13",
        follows: true,
        followed: true,
        followers: 180,
        posts: 45,
        following: 120
    },
    {
        username: "coubridge4",
        joined_at: "2024-01-05",
        bio: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
        profile_image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
        follows_user: true,
        user_id: "13",
        follows: true,
        followed: true,
        followers: 180,
        posts: 45,
        following: 120
    },
    {
        username: "gadranj",
        joined_at: "2024-01-05",
        bio: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
        profile_image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
        follows_user: true,
        user_id: "13",
        follows: true,
        followed: true,
        followers: 180,
        posts: 45,
        following: 120
    },
    {
        username: "rwoolandi",
        joined_at: "2024-01-05",
        bio: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
        profile_image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
        follows_user: true,
        user_id: "13",
        follows: true,
        followed: true,
        followers: 180,
        posts: 45,
        following: 120
    },
    {
        username: "mgravesh",
        joined_at: "2024-01-05",
        bio: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
        profile_image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
        follows_user: true,
        user_id: "13",
        follows: true,
        followed: true,
        followers: 180,
        posts: 45,
        following: 120
    },
    {
        username: "abollandg",
        joined_at: "2024-01-05",
        bio: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
        profile_image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
        follows_user: true,
        user_id: "13",
        follows: true,
        followed: true,
        followers: 180,
        posts: 45,
        following: 120
    },
    {
        username: "cpinallaf",
        joined_at: "2024-01-05",
        bio: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
        profile_image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
        follows_user: true,
        user_id: "13",
        follows: true,
        followed: true,
        followers: 180,
        posts: 45,
        following: 120
    },
    {
        username: "ailchuke",
        joined_at: "2024-01-05",
        bio: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
        profile_image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
        follows_user: true,
        user_id: "13",
        follows: true,
        followed: true,
        followers: 180,
        posts: 45,
        following: 120
    },
    {
        username: "lbrozssetd",
        joined_at: "2022-01-05",
        bio: "ptates repudiandae sint et molestiae non recusandae.",
        profile_image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
        follows_user: true,
        user_id: "13",
        follows: true,
        followed: true,
        followers: 180,
        posts: 45,
        following: 120
    },
    {
        username: "ekytley6",
        joined_at: "2022-01-05",
        bio: "ptates repudiandae sint et molestiae non recusandae.",
        profile_image: "https://res.cloudinary.com/dbddkobs4/image/upload/v1694112421/download_a9n1un.jpg",
        follows_user: true,
        user_id: "13",
        follows: true,
        followed: true,
        followers: 180,
        posts: 45,
        following: 120
    }
  ];
  